import { unstable_cache } from 'next/cache';
import { GoogleGenerativeAI, Schema, SchemaType } from '@google/generative-ai';
import { getInstagramFeed } from './instagram';
import { djLineup as fallbackLineup, type DJSlot } from './data/djLineup';

// Define the expected output schema for Gemini
const lineupSchema: Schema = {
  type: SchemaType.ARRAY,
  description: "A chronological list of the next 7 days of events, starting with TODAY.",
  items: {
    type: SchemaType.OBJECT,
    properties: {
      day: {
        type: SchemaType.STRING,
        description: "Full day name (e.g., 'Monday', 'Friday')",
      },
      short: {
        type: SchemaType.STRING,
        description: "3-letter day abbreviation (e.g., 'MON', 'FRI')",
      },
      djName: {
        type: SchemaType.STRING,
        description: "Event Name or DJ Name (e.g., 'Epic Fridays', 'Ladies Affair')",
      },
      genre: {
        type: SchemaType.STRING,
        description: "Music Genre or Main Theme (e.g., 'Afrobeats / Dancehall', 'PS/FIFA & Pool')",
      },
      time: {
        type: SchemaType.STRING,
        description: "Time of the event (e.g., '10PM – 4AM', '9PM – 2AM')",
      },
      isSpecial: {
        type: SchemaType.BOOLEAN,
        description: "True if this is a major weekend event or special promo.",
      },
      specialLabel: {
        type: SchemaType.STRING,
        description: "Short highlight label if special (e.g., 'MAIN EVENT', 'LADIES NIGHT')",
      }
    },
    required: ["day", "short", "djName", "genre", "time"]
  }
};

async function fetchAndParseLineup(): Promise<DJSlot[]> {
  const apiKey = process.env.GOOGLE_AI_API_KEY;
  if (!apiKey || apiKey === 'your_google_ai_api_key_here') {
    console.warn('[Lineup] No Google AI API key. Using fallback.');
    return fallbackLineup;
  }

  // 1. Fetch recent Instagram posts
  const { posts } = await getInstagramFeed(15);
  if (!posts || posts.length === 0) {
    return fallbackLineup;
  }

  const captions = posts
    .map(p => p.caption)
    .filter(Boolean)
    .join('\n\n---\n\n');

  // 2. Setup Gemini
  const genAI = new GoogleGenerativeAI(apiKey);
  const model = genAI.getGenerativeModel({
    model: 'gemini-2.5-flash',
    generationConfig: {
      temperature: 0.2,
      responseMimeType: "application/json",
      responseSchema: lineupSchema,
    }
  });

  // 3. Ask Gemini to parse the next 7 days
  const today = new Date().toLocaleDateString('en-US', { weekday: 'long' });
  
  const prompt = `
You are an expert club promoter and event planner. 
I am providing you with the recent Instagram captions from 'Paddock Lounge'.

Your task is to generate a 7-day event lineup for the club.
1. Start the lineup with TODAY'S day of the week (${today}).
2. Create exactly 7 consecutive days in order (e.g. if today is Friday, output: Friday, Saturday, Sunday, Monday, Tuesday, Wednesday, Thursday).
3. Read the provided Instagram captions to find specific events for specific days. 
4. If the captions mention an event for a day, extract the Event Name/DJ Name, Genre, and Time.
5. If a day is NOT mentioned in the captions, fill it in with a plausible standard club schedule based on typical lounge operations, but keep it generic (e.g., "Chill / Lounge", "7PM - 1AM").
6. Set "isSpecial" to true and provide a "specialLabel" for major weekend nights (Friday/Saturday) or explicitly promoted nights in the captions.

Instagram Captions:
${captions}
  `;

  try {
    const result = await model.generateContent(prompt);
    const text = result.response.text();
    const lineup = JSON.parse(text) as DJSlot[];
    
    if (!Array.isArray(lineup) || lineup.length < 7) {
      throw new Error("Invalid lineup format generated by AI.");
    }
    
    return lineup.slice(0, 7); // Ensure exactly 7 days
  } catch (error) {
    console.error('[Lineup] Failed to parse dynamic lineup via AI:', error);
    return fallbackLineup;
  }
}

// Cache the AI output for 2 hours (7200 seconds) to avoid quota limits
export const getDynamicLineup = unstable_cache(
  fetchAndParseLineup,
  ['dynamic-instagram-lineup'],
  { revalidate: 7200 }
);
